### ISSUE TITLE
希望可以增加调节当前壁纸的功能

### ISSUE THREAD

**Issue by noahhhi** [Steve-Mr/WallpaperTunnel#10]
遇到个问题是一些壁纸软件没有分享壁纸这个操作，WallpaperTunnel想用步骤变成：设置壁纸-通过命令保存获取当前壁纸-点开软件进行分享，另一款软件Blurone是可以直接获取当前壁纸进行调节设置。
我一直在用Blurone这款软件，但是它在新系统上不是很稳定，希望WallpaperTunnel能平替它。

**Comment by Steve-Mr** [comment]
https://github.com/Steve-Mr/WallpaperTunnel/releases/tag/v8
临时加回来了桌面图标，从桌面图标打开就是当前的主屏壁纸，理论上应该和分享过来的一样，但是没有仔细测试。

后面应该会把这个功能移动到壁纸历史那个 activity 当中，这样的话能直接选以锁屏的壁纸还是主屏的壁纸修改，现在的这个方法只获取了主屏。不过最近时间有点紧张可能不会太快去做。

另外老实讲我这个能力所限大概也没多稳定。

**Comment by noahhhi** [comment]
> https://github.com/Steve-Mr/WallpaperTunnel/releases/tag/v8
> 临时加回来了桌面图标，从桌面图标打开就是当前的主屏壁纸，理论上应该和分享过来的一样，但是没有仔细测试。
> 
> 后面应该会把这个功能移动到壁纸历史那个 activity 当中，这样的话能直接选以锁屏的壁纸还是主屏的壁纸修改，现在的这个方法只获取了主屏。不过最近时间有点紧张可能不会太快去做。
> 
> 另外老实讲我这个能力所限大概也没多稳定。

非常感谢<3
