### ISSUE TITLE
Unable to install on Android 10

### ISSUE THREAD

**Issue by Suzuha08** [Steve-Mr/WallpaperTunnel#8]
软件包无法解析

**Comment by Steve-Mr** [comment]
目前支持的最低版本是 Android 11，现在调用的一些 api 在 11 以后的系统上才有。
也许接下来几天或者下周可以做一下Android 10 的支持，不过只能说有这个想法我还不能保证。

**Comment by Steve-Mr** [comment]
现在在 prerelease 中最新的已经支持了 Android10，受限于精力可能在 ui 和功能上有一些缺陷
